# NASA Docket No. GSC-19606-1, and identified as Test Utilities Python
# package to facilitate testing software with the open source COSMOS
# ground system"
#
# Copyright (c) 2025 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for tracking and reporting test pass/fail and test step pass/fail."""

import inspect
import random
import string
from typing import List, Optional, Dict
from .requirement_utils import RequirementTracker
from .event_utils import capture_events_for_script_logging, start_background_packet_logging, print_events_to_log, stop_background_packet_logging
from .telemetry_utils import report_telemetry
from .system_config import UNIQUE_LOG_IDENTIFIER_LENGTH
from openc3.script.suite import Group

# Global variables
current_test_stack: List[Dict] = []


def test_initialization(test_target_list: List[str], packets_to_report: Optional[List[List[str]]] = None, override_test_name: Optional[str] = None, override_type: Optional[str] = None):
    """
    Initialize a new test with common startup steps.
    
    This function sets up the test environment, including event logging, telemetry reporting,
    and background packet logging. It also manages the test hierarchy structure and initializes
    a new RequirementTracker for this test level.
    
    A unique logging identifier is automatically generated by appending a short random string
    to the test name. This ensures that background packet logging operates independently for
    each test instance, even when the same test is run multiple times with different targets
    or in parallel execution scenarios.
    
    Args:
        test_target_list (List[str]): A list of target names for event logging and packet logging.
        packets_to_report (Optional[List[List[str]]]): A list of [target, packet] pairs to report telemetry for.
                                                       Defaults to None.
        override_test_name (Optional[str]): Override the auto-determined test name. If not provided,
                                           the test name is automatically determined from the calling
                                           function (or class name if called from setup()). Defaults to None.
        override_type (Optional[str]): Override the test type label (e.g., "Suite", "Integration", "Custom").
                                      If not provided, uses "Group" for setup() calls or "Test" otherwise.
                                      Defaults to None.
    
    Raises:
        ValueError: If test_target_list is empty.
    
    Note:
        - Test name is auto-determined: class name for setup(), function name otherwise
        - Test type is auto-determined: "Group" for setup(), "Test" otherwise
        - Creates a new RequirementTracker for this test level.
        - Sets initial status to "U" (Untested) in its own tracker and all parent trackers.
        - Initializes background packet logging with a unique identifier (test_name + random suffix)
          to prevent conflicts when the same test runs with different targets (paralellel execution on different targets).
        - Initializes event capturing for script logging.
        - If packets_to_report is provided, it initializes telemetry reporting for those packets.
    
    Examples:
        test_initialization(["SPACECRAFT"], [["SPACECRAFT", "POWER_TLM"]])
        test_initialization(["SPACECRAFT"], override_test_name="Custom Test Name")
        test_initialization(["SPACECRAFT"], override_test_name="Full Mission Suite", override_type="Suite")
    """
    if not test_target_list:
        raise ValueError("test_target_list must contain at least one target")
    
    global current_test_stack
    
    # Determine test name and type
    if override_test_name:
        test_name = override_test_name
        # If override_type is provided, use it; otherwise default to "Test"
        test_type = override_type if override_type else "Test"
    else:
        # Get caller context to auto-determine test name
        caller_frame = inspect.currentframe().f_back
        caller_function_name = caller_frame.f_code.co_name if caller_frame else "unknown"
        
        if caller_function_name == 'setup' and 'self' in (caller_frame.f_locals if caller_frame else {}):
            # Use class name (Group) for calls from setup(), NOTE: This may be the "suite" as well, use the override for type in that case
            test_name = caller_frame.f_locals['self'].__class__.__name__
            test_type = override_type if override_type else "Group"
        else:
            # Use function name for calls from individual tests
            test_name = caller_function_name
            test_type = override_type if override_type else "Test"
    
    # Create unique logging identifier using short random string
    random_suffix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=UNIQUE_LOG_IDENTIFIER_LENGTH))
    unique_log_name = f"{test_name}_{random_suffix}"
    
    new_test = {
        "name": test_name,
        "status": "U",
        "targets": test_target_list.copy(),  # Copy the list
        "packets_to_report": [pair.copy() for pair in (packets_to_report or [])],  # Deep copy
        "children": [],  # NEW empty list for each test
        "tracker": RequirementTracker(),  # NEW tracker for each test
        "parent": None,
        "unique_log_name": unique_log_name  # Store unique identifier for logging
    }
    
    # Initialize test status
    new_test["tracker"].set_requirement(test_name, "U", f"{test_type} {test_name} initialized")
    
    if current_test_stack:
        parent = current_test_stack[-1]
        new_test["parent"] = parent
        parent["children"].append(new_test)
        
        # Initialize test status in all parent trackers
        while parent:
            parent["tracker"].set_requirement(test_name, "U", f"Subtest {test_name} initialized")
            parent = parent["parent"]
    
    current_test_stack.append(new_test)
    
    # Format target string for printing
    if len(test_target_list) == 1:
        target_str = test_target_list[0]
    elif len(test_target_list) == 2:
        target_str = f"{test_target_list[0]} and {test_target_list[1]}"
    else:
        target_str = ", ".join(test_target_list[:-1]) + f", and {test_target_list[-1]}"
    
    # Print banner with determined type
    Group.print( "")
    Group.print( "|******************************************************************************")
    Group.print(f"| {test_type} Start:")
    Group.print(f"|     Testing {test_name}")
    Group.print(f"|     on {target_str}")
    Group.print( "|******************************************************************************")
    Group.print( "")
    
    # Start background packet logging with unique identifier
    start_background_packet_logging(test_target_list, unique_log_name)
    
    # Capture events for script logging
    capture_events_for_script_logging(test_target_list)
     
    # Report telemetry for specified packets
    if packets_to_report:
        for target, packet in packets_to_report:
            report_telemetry(target, packet, 1, True)
    
    # This print line is just for the larger cosmos log, not the summary
    print(f" --> Test {test_name} has been initialized.")


def test_step_start(step_name: str, track_step_status: bool = False) -> int:
    """
    Mark the start of a test step and initialize its tracking.
    
    This function creates a new step within the current test, assigns it a number,
    and sets up tracking for its Pass/Fail status. It also prints the step information
    and any preceding events to the log.
    
    Args:
        step_name (str): A string that appropriately identifies what is being tested in this step.
        track_step_status (bool): If True, initializes and tracks step status in the current test's tracker. 
                                  This setting is remembered for the corresponding test_step_end call. 
                                  Defaults to False.
    
    Returns:
        int: The number assigned to this step within the current test.
    
    Raises:
        ValueError: If test_initialization() has not been called before this function.
    
    Note:
        - If track_step_status is True, it initializes the step's status in the current test's tracker.
        - The track_step_status setting is stored with the step and used in the corresponding test_step_end call.
    
    Requires:
        At least one test_initialization() must have been called before this function.
        This ensures that script logging is properly set up for test_print calls.
    
    Example:
        step_num = test_step_start("Initialize Power Subsystem", track_step_status=True)
    """
    global current_test_stack
    
    if not current_test_stack:
        raise ValueError("test_initialization must be called before test_step_start")
    
    current_test = current_test_stack[-1]
    step_num = len([child for child in current_test["children"] if "step_num" in child]) + 1
    
    new_step = {
        "name": step_name,
        "status": "U",
        "step_num": step_num,
        "track_step_status": track_step_status
    }
    current_test["children"].append(new_step)
    
    if track_step_status:
        step_id = f"{current_test['name']}, Step {step_num}"
        
        # Initialize step status in current test's tracker
        current_test["tracker"].set_requirement(step_id, "U", f"Step started: {step_name}")
        
        # Propagate step initialization to parent trackers (just like test initialization)
        parent = current_test["parent"]
        while parent:
            parent["tracker"].set_requirement(step_id, "U", f"Substep from {current_test['name']}: {step_name}")
            parent = parent["parent"]
    
    # Print any events from before this call
    print_events_to_log()
    
    Group.print( "")
    Group.print( "|******************************************************************************")
    Group.print(f"|  Step {step_num}.0: {step_name}")
    Group.print( "|******************************************************************************")
    
    return step_num


def test_step_end(step_result: str, result_text: Optional[str] = None) -> str:
    """
    Mark the end of a test step, report its status, and update the test hierarchy.
    
    This function finalizes a test step by setting and reporting its status. It processes
    the provided result, normalizes it, and updates the current step's status in the test
    hierarchy. If step status tracking was enabled in the corresponding test_step_start,
    it also updates the status in the current test's tracker.
    
    Args:
        step_result (str): The result of the test step. Accepted values are "P", "F", "Pass",
                           or "Fail" (case-insensitive).
        result_text (Optional[str]): Additional text to describe the result. Defaults to None.
    
    Returns:
        str: The normalized result ("P" for Pass or "F" for Fail).
    
    Raises:
        ValueError: If test_step_start has not been called before this function, or if there
                    is no active step to end.
    
    Requires:
        At least one test_initialization() must have been called before this function to ensure
        proper script logging setup.
    
    Note:
        - The status set here contributes to determining the overall status of the parent test.
        - If step status tracking was enabled in test_step_start, it updates the status
          in the current test's tracker.
    
    Example:
        result = test_step_end("Pass", "Power subsystem initialized successfully")
    """
    global current_test_stack
    
    if not current_test_stack:
        raise ValueError("test_step_start must be called before test_step_end")
    
    current_test = current_test_stack[-1]
    if not current_test["children"] or "step_num" not in current_test["children"][-1]:
        raise ValueError("No active step to end")
    
    current_step = current_test["children"][-1]
    
    normalized_result = "P" if step_result.upper() in ["P", "PASS"] else "F"
    current_step["status"] = normalized_result
    
    # Use the track_step_status value from the step itself
    if current_step.get("track_step_status", False):
        step_id = f"{current_test['name']}, Step {current_step['step_num']}"
        
        # Update status in current test's tracker
        current_test["tracker"].set_requirement(step_id, normalized_result, result_text or f"Step ended: {current_step['name']}")
        
        # Propagate step status to parent trackers (just like test status propagation)
        parent = current_test["parent"]
        while parent:
            parent["tracker"].set_requirement(step_id, normalized_result, f"Substep from {current_test['name']}: {result_text or current_step['name']}")
            parent = parent["parent"]
    
    # print any events left over from the step into the COSMOS log
    print_events_to_log()
    
    # Report the status for the log (spaces to provide normailized view of the print-out)
    Group.print(     "|------------------------------------------------------------------------------")
    Group.print(     "| Step Status:")
    Group.print(    f"|     Step Number: {current_step['step_num']}, P/F Status: {normalized_result}")
    if result_text:
        Group.print(f"|     Result: {result_text}")
    Group.print(     "|------------------------------------------------------------------------------")
    
    #return the "Pass/Fail" of the step
    return normalized_result


def test_end() -> str:
    """
    End the current test, report its overall status, and perform common wrap-up steps.
    
    This function finalizes the current test by determining its overall status based on its children,
    updating the requirement tracker, stopping background logging, and generating reports.
    It marks the completion of a test hierarchy level and propagates the status to parent tests.
    
    Returns:
        str: The overall status of the test ("P" for Pass or "F" for Fail).
    
    Raises:
        ValueError: If test_initialization has not been called before this function.
    
    Note:
        - It checks for and reports any incomplete subtests.
        - Determines overall status based on all child tests/steps. The test fails if any child fails or is untested.
        - Updates the test's status in its own tracker and all parent trackers.
        - Prints final telemetry for packets specified at initialization.
        - Generates and prints a status report for the current test using its own tracker.
        - Stops background packet logging for this test.
    
    Requires:
        At least one test_initialization() must have been called before this function.
    
    Example:
        final_status = test_end()
    """
    global current_test_stack
    
    if not current_test_stack:
        raise ValueError("test_initialization must be called before test_end")
    
    current_test = current_test_stack.pop()
    test_name = current_test["name"]
    unique_log_name = current_test["unique_log_name"]
    
    # Check for incomplete subtests (tests without step_num)
    incomplete_subtests = [child["name"] for child in current_test["children"] 
                           if "step_num" not in child and child.get("status") == "U"]
    
    # Check for incomplete steps (steps with step_num)
    incomplete_steps = [f"Step {child['step_num']}: {child['name']}" 
                       for child in current_test["children"] 
                       if "step_num" in child and child.get("status") == "U"]
    
    if incomplete_subtests:
        warning_msg = f" <!> Warning: The following subtests were not completed: {', '.join(incomplete_subtests)}"
        Group.print(warning_msg)
     
    if incomplete_steps:
        warning_msg = f" <!> Warning: The following steps were not completed: {', '.join(incomplete_steps)}"
        Group.print(warning_msg)
     
    # Print any events left over from the test
    print_events_to_log()
    
    print("\n|******************************************************************************")
    print( f"|  Test Wrap-up for: {test_name}")
    print(  "|******************************************************************************")
    
    wrapup_step_num = 1
    
    if current_test["packets_to_report"]:
        print("\n|******************************************************************************")
        print( f"|  Wrap-up Step {wrapup_step_num}: Final Telemetry Packet Report(s) of those specified in test_initialization")
        print(  "|******************************************************************************")
    
        # Report on the packets specified during test initialization
        for target, packet in current_test["packets_to_report"]:
            report_telemetry(target, packet, 1)
            
        wrapup_step_num += 1
    
    
    print("\n|******************************************************************************")
    print( f"|  Wrap-up Step {wrapup_step_num}: Stop reporting packets to seperate logs.")
    print(  "|******************************************************************************")
    
    stop_background_packet_logging(unique_log_name) # stops logging to separate file if started by this test
    wrapup_step_num += 1
    
    
    print("\n|******************************************************************************")
    print( f"|  Wrap-up Step {wrapup_step_num}: Requirement report for {test_name}")
    print(  "|******************************************************************************")
    
    Group.print("\nTest components contributing to the status:")
    
    for child in current_test["children"]:
        if "step_num" in child:
            child_string = f"Step {child['step_num']}: {child['name']}"
        else:
            child_string = child['name']  # Sub-tests are just represented by their name
        child_status = child.get("status", "U")  # Default to 'U' if status is not set
        Group.print(f"  {child_string}: {child_status}")
    
    # DETERMINE OVERALL TEST STATUS
    overall_status = "F"  # Default to Fail
    
    # Check for no children and print warning if applicable
    if not current_test["children"]:
        warning_msg = f" <!> Warning: Test '{test_name}' had no steps or sub-tests and is marked as Failed due to this."
        Group.print(warning_msg)
    elif all(child.get("status", "F") == "P" for child in current_test["children"]):
        # Change to Pass only if all children passed (no "U" or "F" statuses)
        overall_status = "P"
    
    current_test["status"] = overall_status
    
    # Update status in current test's tracker
    current_test["tracker"].set_requirement(test_name, overall_status, f"Test {test_name} completed")
    
    # Propagate status to parent trackers
    parent = current_test["parent"]
    while parent:
        parent["tracker"].set_requirement(test_name, overall_status, f"Subtest {test_name} completed")
        parent = parent["parent"]
    
    # Generate and print the requirement report for the current test
    report = current_test["tracker"].generate_requirements_report()
    Group.print(report)
     
    Group.print("\n|------------------------------------------------------------------------------")
    Group.print( f"|  END OF TEST: {test_name} - Test Status: {overall_status}")
    Group.print(  "|------------------------------------------------------------------------------")
    
    return overall_status    
